"""empty message

Revision ID: 2a574c0d198a
Revises: 383b3b662ab8
Create Date: 2021-04-14 13:54:54.290266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a574c0d198a'
down_revision = '383b3b662ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('input_img', sa.VARCHAR(length=100), nullable=False),
    sa.Column('result_img', sa.VARCHAR(length=100), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
