"""empty message

Revision ID: 32ef638f3906
Revises: 6a3ba023da5a
Create Date: 2021-04-12 17:06:42.337378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ef638f3906'
down_revision = '6a3ba023da5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.add_column('input_', sa.Column('result_img', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_', 'result_img')
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inputimage_id', sa.INTEGER(), nullable=True),
    sa.Column('return_img', sa.VARCHAR(length=100), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['inputimage_id'], ['input_.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
