"""empty message

Revision ID: 383b3b662ab8
Revises: 32ef638f3906
Create Date: 2021-04-12 17:08:58.261732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383b3b662ab8'
down_revision = '32ef638f3906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_img', sa.String(length=100), nullable=False),
    sa.Column('result_img', sa.String(length=100), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('input_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('input_img', sa.VARCHAR(length=100), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('result_img', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('image_')
    # ### end Alembic commands ###
