"""empty message

Revision ID: 7908f02934f7
Revises: e2348daeb058
Create Date: 2021-04-14 15:47:34.548394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7908f02934f7'
down_revision = 'e2348daeb058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_info', sa.Column('image_path', sa.String(length=100), nullable=False))
    op.drop_column('upload_info', 'image_list')
    op.drop_column('upload_info', 'image_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_info', sa.Column('image_name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('upload_info', sa.Column('image_list', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('upload_info', 'image_path')
    # ### end Alembic commands ###
