"""empty message

Revision ID: c00d7f0d3687
Revises: ecff32a87b3e
Create Date: 2021-04-15 14:10:42.240251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00d7f0d3687'
down_revision = 'ecff32a87b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modellist_id', sa.Integer(), nullable=True),
    sa.Column('image_name', sa.String(length=1000), nullable=False),
    sa.Column('image_path', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['modellist_id'], ['model_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_info')
    # ### end Alembic commands ###
